### ISSUE TITLE
Seems missing .csproj file

### ISSUE THREAD

**Issue by lousaibiao** [matthamil/Chatazon#1]
I got this error when I restore it.
error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
Seems missing .csproj file.

**Comment by matthamil** [comment]
This project was created using the .NET Core CLI and edited with VS Code. Neither of these generate a `.csproj` file like Visual Studio would. You are welcome to submit a PR with a .csproj file for the project for those who might be running this project in Visual Studio :)
